/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:290165d4-cfd7-4fd0-8c94-cf4e5e68eddf",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_QbmRY7rNx",
    "aws_user_pools_web_client_id": "5m2ogogpkanbhcvoevjp3l89cc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://i5u5tjdog5ccplztmzzsahu54i.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-o3ukhg7btzfyjdxuwhyv4p6ute"
};


export default awsmobile;
